site_name: Go-Smart Simulation Architecture Documentation
pages:
    - Home: index.md
    - Comparison: comparison.md
    - Errors: errors.md
    - GSSA XML Format: gssa-xml.md
    - Families: families.md
    - Clinical Domain Model:
        - Overview: 'cdm/overview.md'
        - Algorithms: 'cdm/algorithms.md'
        - Contexts: 'cdm/contexts.md'
        - Parameters: 'cdm/parameters.md'
    - Server:
        - Overview: 'server/overview.md'
        - Router: 'server/router.md'
        - Executables: 'server/executables.md'
        - Database: 'server/database.md'
        - Transferrers: 'server/transferrers.md'
    - Docker Workflows:
        - Overview: 'docker/overview.md'
        - Python Container Module: 'docker/container-module.md'
        - FEniCS Family: 'docker/fenics.md'
theme: readthedocs
